In [2]:
from sklearn.preprocessing import MinMaxScaler

data = [[-1, 2], [-0.5, 6], [0, 10], [1, 18]]
import pandas as pd


In [3]:
pd.DataFrame(data)
scaler = MinMaxScaler() #实例化
scaler = scaler.fit(data) #fit，在这里本质是生成min(x)和max(x)
result = scaler.transform(data) #通过接口导出结果
result

array([[0.  , 0.  ],
       [0.25, 0.25],
       [0.5 , 0.5 ],
       [1.  , 1.  ]])

In [5]:
result_ = scaler.fit_transform(data) #训练和导出结果一步达成
scaler.inverse_transform(result)

array([[-1. ,  2. ],
       [-0.5,  6. ],
       [ 0. , 10. ],
       [ 1. , 18. ]])

array([[ 5.  ,  5.  ],
       [ 6.25,  6.25],
       [ 7.5 ,  7.5 ],
       [10.  , 10.  ]])

In [10]:

pd.DataFrame(data)
scaler = MinMaxScaler() #实例化
scaler = scaler.fit(data) #fit，在这里本质是生成min(x)和max(x)
result = scaler.transform(data) #通过接口导出结果
result


In [ ]:

result_ = scaler.fit_transform(data) #训练和导出结果一步达成
scaler.inverse_transform(result)


In [ ]:

data = [[-1, 2], [-0.5, 6], [0, 10], [1, 18]]
scaler = MinMaxScaler(feature_range=[5,10])

## 标准化


In [11]:
from sklearn.preprocessing import StandardScaler

data = [[-1, 2], [-0.5, 6], [0, 10], [1, 18]]
scaler=StandardScaler()

array([[-1. ,  2. ],
       [-0.5,  6. ],
       [ 0. , 10. ],
       [ 1. , 18. ]])

In [12]:
scaler.fit(data)


StandardScaler()

In [13]:
scaler.mean_
scaler.var_

array([ 0.546875, 35.      ])

In [14]:

x_std=scaler.transform(data)
x_std.mean()
x_std.std()


1.0

In [15]:
scaler.fit_transform(data)
scaler.inverse_transform(x_std)

array([[-1. ,  2. ],
       [-0.5,  6. ],
       [ 0. , 10. ],
       [ 1. , 18. ]])

## 分类型特征

In [2]:
import pandas as pd
data = pd.read_csv(r"Narrativedata.csv",index_col=0)

data.loc[:,"Age"] = data.loc[:,"Age"].fillna(data.loc[:,"Age"].median())
#.fillna 在DataFrame里面直接进行填补
data.head(20)


Age     Sex Embarked Survived
0   22.0    male        S       No
1   38.0  female        C      Yes
2   26.0  female        S      Yes
3   35.0  female        S      Yes
4   35.0    male        S       No
5   28.0    male        Q       No
6   54.0    male        S       No
7    2.0    male        S       No
8   27.0  female        S      Yes
9   14.0  female        C      Yes
10   4.0  female        S  Unknown
11  58.0  female        S      Yes
12  20.0    male        S       No
13  39.0    male        S       No
14  14.0  female        S       No
15  55.0  female        S  Unknown
16   2.0    male        Q       No
17  28.0    male        S      Yes
18  31.0  female        S       No
19  28.0  female        C      Yes

## 编码与哑变量


## 二值化分段

In [3]:
data_2=data.copy()

In [7]:
from sklearn.preprocessing import Binarizer

X=data.iloc[:,0].values.reshape(-1,1) #类为特征专用，所以不能使用一维数组
transformer=Binarizer(threshold=30).fit_transform(X)#threshold 界限

transformer

array([[0.],
       [1.],
       [0.],
       [1.],
       [1.],
       [0.],
       [1.],
       [0.],
       [0.],
       [0.],
       [0.],
       [1.],
       [0.],
       [1.],
       [0.],
       [1.],
       [0.],
       [0.],
       [1.],
       [0.],
       [1.],
       [1.],
       [0.],
       [0.],
       [0.],
       [1.],
       [0.],
       [0.],
       [0.],
       [0.],
       [1.],
       [0.],
       [0.],
       [1.],
       [0.],
       [1.],
       [0.],
       [0.],
       [0.],
       [0.],
       [1.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [1.],
       [0.],
       [1.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [1.],
       [1.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [1.],
       [0.],
       [0.],
       [0.],
       [1.],
       [0.],
       [0.],

In [12]:
from sklearn.preprocessing import KBinsDiscretizer
X=data.iloc[:,0].values.reshape(-1,1)
est=KBinsDiscretizer(n_bins=3,encode='ordinal',strategy='uniform')
est.fit_transform(X)
set(est.fit_transform(X).ravel())

{0.0, 1.0, 2.0}

In [15]:
est=KBinsDiscretizer(n_bins=3,encode='onehot',strategy='uniform')
est.fit_transform(X).toarray()

array([[1., 0., 0.],
       [0., 1., 0.],
       [1., 0., 0.],
       ...,
       [0., 1., 0.],
       [1., 0., 0.],
       [0., 1., 0.]])