##  名为回归的分类器

In [1]:
# linear_model
# LogisticRegression Cv 
# SGDClassifier
# SGDRegressor
# log_loss
import pandas as pd
import matplotlib.pyplot as plt
import numpy as np
from sklearn.linear_model import LogisticRegression as LR
from sklearn.datasets import load_breast_cancer
from sklearn.model_selection import train_test_split
from sklearn.metrics import accuracy_score

data=load_breast_cancer()
X=data.data
y=data.target


In [2]:
data.data.shape

(569, 30)

In [3]:
model1=LR(penalty='l1',solver='liblinear',C=0.5,max_iter=1000)
model2=LR(penalty='l2',solver='liblinear',C=0.5,max_iter=1000)


In [4]:
lrl1=model1.fit(X,y)
lrl1.coef_

array([[ 3.98742629,  0.03155133, -0.13504429, -0.01622252,  0.        ,
         0.        ,  0.        ,  0.        ,  0.        ,  0.        ,
         0.        ,  0.50460943,  0.        , -0.07128828,  0.        ,
         0.        ,  0.        ,  0.        ,  0.        ,  0.        ,
         0.        , -0.24545004, -0.1285933 , -0.01440975,  0.        ,
         0.        , -2.0540166 ,  0.        ,  0.        ,  0.        ]])

In [5]:
(lrl1.coef_ !=0)

array([[ True,  True,  True,  True, False, False, False, False, False,
        False, False,  True, False,  True, False, False, False, False,
        False, False, False,  True,  True,  True, False, False,  True,
        False, False, False]])

In [6]:
(lrl1.coef_ !=0).sum(axis=1)

array([10])

In [7]:
lrl2=model2.fit(X,y)
lrl2.coef_

array([[ 1.61358623e+00,  1.00284781e-01,  4.61036191e-02,
        -4.21333984e-03, -9.27388895e-02, -3.00561176e-01,
        -4.53477303e-01, -2.19973055e-01, -1.33257382e-01,
        -1.92654788e-02,  1.87887747e-02,  8.75532438e-01,
         1.31708341e-01, -9.53440922e-02, -9.64408195e-03,
        -2.52457845e-02, -5.83085040e-02, -2.67948347e-02,
        -2.74103894e-02, -6.09326731e-05,  1.28405755e+00,
        -3.00219699e-01, -1.74217870e-01, -2.23449384e-02,
        -1.70489339e-01, -8.77400140e-01, -1.15869741e+00,
        -4.22909464e-01, -4.12968162e-01, -8.66604813e-02]])

In [8]:
(lrl2.coef_ !=0)

array([[ True,  True,  True,  True,  True,  True,  True,  True,  True,
         True,  True,  True,  True,  True,  True,  True,  True,  True,
         True,  True,  True,  True,  True,  True,  True,  True,  True,
         True,  True,  True]])